"""v5 design review fixes

Revision ID: 172e4c8ae384
Revises: 
Create Date: 2026-04-12 01:42:59.506422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172e4c8ae384'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_table', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('proposal_value', sa.Text(), nullable=True),
    sa.Column('proposal_reason', sa.Text(), nullable=True),
    sa.Column('proposal_source', sa.String(length=50), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_code', sa.String(length=20), nullable=True),
    sa.Column('prefecture', sa.String(length=10), nullable=False),
    sa.Column('corporation_name', sa.String(length=200), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('school_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code')
    )
    op.create_table('taxonomy_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_pattern', sa.String(length=200), nullable=False),
    sa.Column('field_category', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_pattern', 'field_category'),
    comment='Persisted human decisions for competition classification'
    )
    op.create_table('crawl_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=True),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('course_type', sa.String(length=10), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('field_category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('discovered_from', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('is_current_year', sa.Boolean(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('pdf_type', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'file_hash'),
    comment='PDF document registry'
    )
    op.create_table('school_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=200), nullable=False),
    sa.Column('alias_type', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_type', sa.String(length=30), nullable=True),
    sa.Column('discovery_method', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'url'),
    comment='School website registry'
    )
    op.create_table('department_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('old_name', sa.String(length=200), nullable=True),
    sa.Column('new_name', sa.String(length=200), nullable=True),
    sa.Column('related_dept_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['related_dept_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_yearly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('intl_students', sa.Integer(), nullable=True),
    sa.Column('graduates', sa.Integer(), nullable=True),
    sa.Column('advanced', sa.Integer(), nullable=True),
    sa.Column('employed', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('prev_enrollment', sa.Integer(), nullable=True),
    sa.Column('dropouts', sa.Integer(), nullable=True),
    sa.Column('dropout_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'fiscal_year', 'revision'),
    comment='Yearly department snapshot, append-only with revision support'
    )
    op.create_index('idx_dept_yearly_current', 'department_yearly', ['department_id', 'fiscal_year'], unique=True, postgresql_where='is_current = true')
    op.create_table('school_year_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('legacy_status', sa.String(length=50), nullable=True),
    sa.Column('excluded_reason', sa.String(length=50), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'fiscal_year'),
    comment='School-year collection status tracking'
    )
    op.create_table('support_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_number', sa.String(length=20), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('first_half_total', sa.Integer(), nullable=True),
    sa.Column('first_half_cat1', sa.Integer(), nullable=True),
    sa.Column('first_half_cat2', sa.Integer(), nullable=True),
    sa.Column('first_half_cat3', sa.Integer(), nullable=True),
    sa.Column('first_half_cat4', sa.Integer(), nullable=True),
    sa.Column('second_half_total', sa.Integer(), nullable=True),
    sa.Column('second_half_cat1', sa.Integer(), nullable=True),
    sa.Column('second_half_cat2', sa.Integer(), nullable=True),
    sa.Column('second_half_cat3', sa.Integer(), nullable=True),
    sa.Column('second_half_cat4', sa.Integer(), nullable=True),
    sa.Column('annual_total', sa.Integer(), nullable=True),
    sa.Column('household_change', sa.Integer(), nullable=True),
    sa.Column('grand_total', sa.Integer(), nullable=True),
    sa.Column('prev_enrollment', sa.Integer(), nullable=True),
    sa.Column('recipient_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'fiscal_year'),
    comment='Support recipient data for 対象比率 sheet'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_recipient')
    op.drop_table('school_year_status')
    op.drop_index('idx_dept_yearly_current', table_name='department_yearly', postgresql_where='is_current = true')
    op.drop_table('department_yearly')
    op.drop_table('department_change')
    op.drop_table('school_site')
    op.drop_table('school_alias')
    op.drop_table('document')
    op.drop_table('department')
    op.drop_table('crawl_job')
    op.drop_table('taxonomy_mapping')
    op.drop_table('school')
    op.drop_table('review_item')
    # ### end Alembic commands ###
