"""v8 add document ingest_status column

Revision ID: d9510cbcb776
Revises: cbb204a26301
Create Date: 2026-04-13 00:15:06.559730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9510cbcb776'
down_revision: Union[str, Sequence[str], None] = 'cbb204a26301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'department',
        'Department identity table',
        existing_comment=None,
        schema=None
    )
    op.add_column('document', sa.Column('ingest_status', sa.String(length=30), nullable=True))
    op.create_table_comment(
        'school',
        'School identity table',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'school',
        existing_comment='School identity table',
        schema=None
    )
    op.drop_column('document', 'ingest_status')
    op.drop_table_comment(
        'department',
        existing_comment='Department identity table',
        schema=None
    )
    # ### end Alembic commands ###
